featureProject/account/urls.py
from django.urls import path 
from . import views
urlpatterns = [
    path('signup/', views.signup,name='signup'),
]

featureProject/boards/urls.py
from django.urls import path
from . import views, classBasedViews
urlpatterns = [
    path('home/', views.home, name='home'),
    path('board/<pk>/', views.board_topics, name='board'),
    path('board/<pk>/new/', views.new_topic,name='new_topic'),

    path('boardData/', classBasedViews.BoardDetails.as_view(), name='boardData'),
    path('deleteBoard/<pk>/', classBasedViews.deleteBoard.as_view(), name='deleteBoard'),
    

]

featureProject/featureProject/urls.py
from django.contrib import admin
from django.urls import path, include
from boards import views

from rest_framework.routers import DefaultRouter
from boards import viewsets

router = DefaultRouter()
router.register('board', viewsets.BoardsModelViewSet, basename='model')


urlpatterns = [
    path('model/', include(router.urls)),
    path('quora/',include('boards.urls'), name='quora'),
    path('account/',include('account.urls'), name='account'),
    path('admin/', admin.site.urls),
]

featureProject/ORM/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)

class Musician(models.Model):
    musician = models.ForeignKey(Person, on_delete=models.CASCADE)
    instrument = models.CharField(max_length=20)

class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    num_stars = models.IntegerField()
    lable_name = models.ForeignKey(RecordLabel, on_delete=models.PROTECT)

class RecordLabel(models.Model):
    lable_name = models.CharField(max_length=20)
    musicians = models.ManyToManyField(Musician, on_delete=models.CASCADE)

featureProject/account/models.py
from django.db import models

# Create your models here.

featureProject/boards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name 

class Topic(models.Model):
    subject = models.CharField(max_length=30)
    last_updated = models.DateTimeField(auto_now_add=True)
    # if board has topics associated with it. Board can not be deleted
    board = models.ForeignKey(Board, related_name="topics", on_delete=models.PROTECT) 
    starter = models.ForeignKey(User, related_name="topics", on_delete=models.CASCADE)

class Post(models.Model):
    message = models.TextField()
    topic = models.ForeignKey(Topic, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    # '+' sign in related field indicates we dont need reverse relationships 
    updated_by = models.ForeignKey(User, null = True, related_name="+", on_delete=models.CASCADE)

featureProject/ORM/views.py
from django.shortcuts import render

# Create your views here.

featureProject/account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout 
# Create your views here.

def signup(request):
    print("******request.POST ", request.POST)
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('home')
    else: form = UserCreationForm()
    # form = UserCreationForm()
    return render(request,"accounts/signup.html", {'form':form})

featureProject/boards/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import Board,Topic,Post
from django.contrib.auth.models import User
# Create your views here.

def home(request):
    boards = Board.objects.all()
    board_names = []
    for board in boards:
        board_names.append(board.name)
    context={'board_names':boards}
    template_name = 'boards_app\home.html'
    return render(request, template_name,context)

def board_topics(request, pk):
    try:
        board = Board.objects.get(id=pk)
        template_name = 'boards_app\\topics.html'
        return render(request, template_name, {'board': board})
    except Board.DoesNotExist as msg:
        raise Http404

def new_topic(request, pk):
    board = Board.objects.get(pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()  # TODO: get the currently logged in user

        topic = Topic.objects.create(
            subject=subject,
            board=board,
            starter=user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )

        return redirect('board', pk=board.pk)  # TODO: redirect to the created topic page

    return render(request, 'boards_app\\new_topic.html', {'board': board})

featureProject/templates/accounts/signup.html
{% extends 'boards_app/base.html' %}

{% block body %}
  <h2>Sign up</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create an account</button>
  </form>
{% endblock %}

featureProject/templates/boards_app/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Delicious+Handrawn&display=swap" rel="stylesheet">
    {% block stylesheet %}{% endblock %} 
 </head>
  <body>
    {% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">QUORA</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">{{ user.username }}</a>
            </li>
          </ul>
        </div>

      </nav>
  
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
    {% endblock %}
  </body>
</html>

featureProject/templates/boards_app/home.html
{% extends 'boards_app/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in board_names %}
        <tr>
          <td>
            <a href="{% url 'board' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

featureProject/templates/boards_app/new_topic.html
{% extends 'boards_app/base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">  Post </button>
  </form>
{% endblock %}

featureProject/templates/boards_app/topics.html
{% extends 'boards_app/base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in board.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}